#!python3
from open_file import read_html
from make_ical import make_ical
from get_file import get_page
from sys import argv
if __name__ == '__main__':
    if len(argv) != 3:
        raise Exception('format is: ./main input output')
    page = get_page(argv[1])
    df = read_html(page)
    make_ical(df, argv[2])